### ISSUE TITLE
Circular linked list

### ISSUE THREAD

**Issue by biswanathamz** [biswanathamz/Galax-c-pp#3]
**Need to implement - Douby linked list.** 
**Path -** - _Galax-c-pp/DS/LinkedList/LinkedList_using_struct/circularln.cpp_
**Code Reference** - _Galax-c-pp/DS/LinkedList/LinkedList_using_struct/singleln.cpp_

**BRANCH** - circular_linked_list

**Comment by kaustavcs** [comment]
Dev Completed, Put Code Review Comments and Merge.

**Comment by biswanathamz** [comment]
@kaustavcs Please add - // """Code is contributed by Kaustav Ghosh (https://github.com/kaustavcs) """ at the top of your code. 

@knightrostreamer  - refer this.

**Comment by biswanathamz** [comment]
@kaustavcs Code is merged with the master. Good Job.
